### ISSUE TITLE
Adding Firefox OS section on mozillaindia homepage

### ISSUE THREAD

**Issue by swarnava** [MozillaIndia/homepage#49]
Since Firefox OS release is near, we should add a section of Firefox OS.

**Comment by GirishRawat** [comment]
Should we link it to the mozilla.org's firefox OS webpage or create a new one? https://www.mozilla.org/en-US/firefox/os/2.0/

**Comment by dolftax** [comment]
@GirishRawat +1 / Send us a PR!

**Comment by swarnava** [comment]
I think we should add https://www.mozilla.org/en-US/firefox/os/ instead of which is currently redirecting to https://www.mozilla.org/en-US/firefox/os/1.3t/ which is designed for Tarako(Indian) devices!

**Comment by asdofindia** [comment]
Hey, a link works for now (although I wonder if the top navigation bar is the right place for it).

But I was thinking we could have an entire call to action kind of thing for Firefox OS. Since Mozilla's goals are to push Firefox OS really hard. Maybe that needs a site redesign that's why I've added the redesign milestone to this. 

@dolftax, can you reopen this or should we create another tracking issue with this larger goal in mind?

**Comment by dolftax** [comment]
@asdofindia Let this fit in the current version. Open up a branch in this repo and start working on the re-design.
