### ISSUE TITLE
No link in Apply to be MahaDev

### ISSUE THREAD

**Issue by Dipanks** [MozillaIndia/homepage#85]
http://devs.mozillaindia.org/start/

Tried to apply to 'Apply to be a MahaDev' program for Indian Mozillians. But there was no actual link for the application form.

The page however states
"If you haven't done so already, fill this application form and one of us will get in touch with you."

And I wanted to fill up this form because I wanted to be guided by someone from Mozilla to help me start contributing. Since I could not write there, I am dropping it here. If someone can act as a mentor/guide, it would be awesome!

Thank You

**Comment by asdofindia** [comment]
Hi Dipanks, thanks for making this issue.

The bug is already open at MozillaIndia/mozillaindia.github.io#6

If you are comfortable and willing to learn new technologies and spend hours fixing a problem by yourself, you can [contact me](https://asd.learnlearn.in/about/#contact) and I can help you start contributing.
